micronaut:
  application:
    name: cubedashboardpull
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
micronaut:
  server:
    cors:
      enabled: true
---
micronaut:
  security:
    redirect:
      unauthorized:
        url: '/oauth/login/cognito'
    oauth2:
      clients:
        cognito:
          client-id: '6k4d4vo78ihe4kjv9cegs2crc6' # demo client id
          client-secret: 'mil0sq088ii31p32rpgllofrnl5f71kgjlcsjmdcv66u4mju52' # demo client secret
          openid:
            issuer: 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ryzdYRYvn/' # demo user pool
    endpoints:
      logout:
        get-allowed: true
    authentication: idtoken
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            awscognito:
              url: 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ryzdYRYvn/.well-known/jwks.json'
---
app:
  login-redirect: 'http://localhost:5000'
  param-token: 'token'