micronaut:
  application:
    name: cubedashboardpull
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
micronaut:
  security:
    intercept-url-map:
      - pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/*
        http-method: GET
        access:
          - isAnonymous()
---
micronaut:
  server:
    cors:
      enabled: true
---
micronaut:
  router:
    versioning:
      enabled: true
---
micronaut:
  security:
    authentication: idtoken
    redirect:
      unauthorized:
        url: '/unauthorized'
      forbidden:
        url: '/denied'
      logout: '/ui'
    oauth2:
      clients:
        cognito:
          client-id: '6k4d4vo78ihe4kjv9cegs2crc6' # demo client id
          client-secret: 'mil0sq088ii31p32rpgllofrnl5f71kgjlcsjmdcv66u4mju52' # demo client secret
          openid:
            issuer: 'https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ryzdYRYvn/' # demo user pool
    endpoints:
      logout:
        get-allowed: true
---
app:
  login-redirect: 'http://localhost:5000'
  param-token: 'token'